// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMqIXOkgaEnLrICxeoE-_o2MJcDR98Lws',
    appId: '1:422872195312:web:300efe5f4ee5d6d5d7e235',
    messagingSenderId: '422872195312',
    projectId: 'streameee-app',
    authDomain: 'streameee-app.firebaseapp.com',
    databaseURL: 'https://streameee-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'streameee-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGWhuyzuMOyVcxgrxlRG-JWyQkno7drk',
    appId: '1:422872195312:android:57f79777f933ee54d7e235',
    messagingSenderId: '422872195312',
    projectId: 'streameee-app',
    databaseURL: 'https://streameee-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'streameee-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ozHB4_j_lFxcDARVYIBz7sFCkEbacoM',
    appId: '1:422872195312:ios:48250f2b63f82648d7e235',
    messagingSenderId: '422872195312',
    projectId: 'streameee-app',
    databaseURL: 'https://streameee-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'streameee-app.firebasestorage.app',
    iosBundleId: 'com.streameee.app',
  );

}